### ISSUE TITLE
Text data about WikiKG90M-LSC.

### ISSUE THREAD

**Issue by CheaSim** [apoorvumang/kgt5#1]
This work is great! I wonder if you could release the text of entity and relation in the WikiKG90M-LSC.

**Comment by apoorvumang** [comment]
Thanks for your interest! You can download them here (eg. use wget) and load with pickle

https://storage.googleapis.com/kgt5-wikikg90mv2/ent_alias_list.pickle

https://storage.googleapis.com/kgt5-wikikg90mv2/rel_alias_list.pickle

Format: Item at i-th position in the list is the text for entity i in WikiKG90Mv2 (similarly for relation).

**Comment by CheaSim** [comment]
Thanks for your sharing.
