### ISSUE TITLE
KGC data split

### ISSUE THREAD

**Issue by screemix** [apoorvumang/kgt5#17]
Hi Apoorv,

thank you for sharing the repo on KGT5. I am sorry for bothering you, but could you please tell me whether there is a link to the dataset split you used for the link prediction task and mentioned in the paper? I can't find it in previous issues + link from the repo leads to the dataset having the same number of connections as an original wikidata5m has. 

Thank you in advance.

**Comment by apoorvumang** [comment]
Hi @screemix and sorry for the delayed response 

We used the same dataset split for wikidata5m that we have linked in the repo. Are you noticing any discrepancy? If so, please elaborate on the issue you are facing so we can better help

**Comment by apoorvumang** [comment]
Do you require test/train split as well or just the mapping files?

**Comment by screemix** [comment]
> Do you require test/train split as well or just the mapping files?

No, in this issue I meant actually the train/test split. I am sorry for misunderstanding. 
Maybe I confused smt, but in the paper you wrote:

> Following prior work (Sun et al., 2019a) we ran- domly drop 50% of edges from all KGs to simulate KG incompleteness. This stochasticity causes different works to have different KGs, making it hard to compare results without re-implementing methods. Ren et al. (2021) implemented all comparison methods using their own KG splits which they have

Did you split the train set to simulate KG incompleteness? And am I right that this is related to link prediction task? I am sorry if I confuse something, but this paragraph is separated from mentioning of the datasets used for both LP and QA tasks (section - 4.1 Datasets), so it isn't clear for me for which task you performed dropping. Would be great if you explain the procedure 'dropping 50% of connections' in more details.

**Comment by apoorvumang** [comment]
The edge dropping thing was required for KGQA, since there is no official test/dev splits of the KG there.

For KGC, we used the same data split as used by other baselines

**Comment by screemix** [comment]
> The edge dropping thing was required for KGQA, since there is no official test/dev splits of the KG there.
> 
> For KGC, we used the same data split as used by other baselines

Thank you for the clarification!
