### ISSUE TITLE
1to1 mapping split issues 

### ISSUE THREAD

**Issue by screemix** [apoorvumang/kgt5#18]
Hi Aproov, 

there already was a question about one-to-one mapping between entities and relations in #5 . You shared the file with the suggested one-to-one mapping. But the issue is, there is one entity without a mapping and about 190 entities that have duplicated names there. Examples of duplicated names are john mclachlan, xing kong, belle vue, etc. An id with a missed name is [Q11159396](https://www.wikidata.org/wiki/Q11159396). 
In the original paper you suggested using the following scheme of resolving such issues with duplicated names: 

> However, multiple entities can have identical canonical mentions; we disambiguate such enti- ties by appending the name with their 1-line description if available. In all other cases of identical canonical mentions we extend each mention with a unique id.

However, while the 1-line descriptions were provided for some entities, for one there was no such option, there no disambiguation scheme at all the [file you shared](https://storage.googleapis.com/t5-kgc-colab/data/wd5m_final_aliases.txt).

<img width="677" alt="Screenshot 2022-08-25 at 13 59 53" src="https://user-images.githubusercontent.com/43718473/186647503-543d6bc9-40d9-4185-9557-21f64dd69198.png">
<img width="679" alt="Screenshot 2022-08-25 at 14 00 09" src="https://user-images.githubusercontent.com/43718473/186647549-0bdd4b54-4cbf-4923-85dd-024b59d93dbb.png">

[Here](https://drive.google.com/file/d/1aGhWaGOLziZvsQkjyoLW3zjOPEQpq32g/view?usp=sharing) I provide the file with an improved 1to1 mapping without the missed element and disambiguated entities by the scheme you described in the paper (e.g. for id Q8044536 duplicated name becomes xing kong_8044536). 

But anyway, I got kind of confused with the mapping you share. There are also more (>300k) entities than overall in wikidata5m. Is the file you shared the same as you used for the verbalisation during your work on KGT5? And did I get and perform you disambiguation scheme in a right way?

Thank you in advance.

**Comment by apoorvumang** [comment]
Hi @screemix , thanks for the detailed response.

Let me check my dataset dumps and i will get back to you in a few hours

**Comment by apoorvumang** [comment]
For the results in the paper we used a slightly different mapping than this. I will upload that and share it with you, that should hopefully solve the issue. Please give me a couple hours for that, and I apologise for the delay

**Comment by apoorvumang** [comment]
Please download following files for the updated mappings. These were the ones used to generate the final results reop

https://storage.googleapis.com/t5-kgc-colab/data/wd5m_aliases_entities_v3.txt
https://storage.googleapis.com/t5-kgc-colab/data/wd5m_aliases_relations_v3.txt

These files don't contain the issue highlighted above, but if you need other data as well please don't hesitate to raise another github issue

![image](https://user-images.githubusercontent.com/1957903/186663918-5d1f84fa-8962-49dd-b33e-0da1177efc7c.png)

**Comment by screemix** [comment]
> Please download following files for the updated mappings. These were the ones used to generate the final results reported in the paper
> 
> https://storage.googleapis.com/t5-kgc-colab/data/wd5m_aliases_entities_v3.txt https://storage.googleapis.com/t5-kgc-colab/data/wd5m_aliases_relations_v3.txt

Thank you! These mapping schemas are actually ok, I tested it and didn't find the issues I described above.
