### ISSUE TITLE
Answering questions

### ISSUE THREAD

**Issue by SergeyPetrakov** [apoorvumang/kgt5#23]
![IMAGE 2022-11-09 11:45:50](https://user-images.githubusercontent.com/32465854/200782595-0abbcbc8-35bb-4a8b-b643-befe524d2ee7.jpg)

I followed your advice to push into the model 
input="predict answer: what can cause a tsunami"
and then 
out = topkSample(input, model, tokenizer, num_samples=5)
But as you can see ther esults are extremely low, but in your notebooks this approach showed good results, can you help me please with this issue

**Comment by apoorvumang** [comment]
Hi @SergeyPetrakov , thanks for your interest!

Are you using the model from here? https://huggingface.co/spaces/apoorvumang/kgt5 . The publicly available models are only trained on the KG completion task and have not been finetuned for QA. Hence they will be good only for KGC. For the results in the paper, we further finetuned the models on QA datasets. To reproduce the results, you will have to finetune the models yourself

**Comment by SergeyPetrakov** [comment]
Hi @apoorvumang, thank you for fast answer!
I have used apoorvumang/kgt5-base-wikikg90mv2 model. May I ask you to share checkpoints of models that you finetuned on QA datasets?

**Comment by apoorvumang** [comment]
Unfortunately we don't have pretrained checkpoints available right now (but we might be adding them soon). Request you to create a new issue for this for tracking
