### ISSUE TITLE
Dataset Link Cannot be Opened

### ISSUE THREAD

**Issue by huihuipiaomiao** [apoorvumang/kgt5#9]
Hello author, I am very happy to read about kgt5. But I have a question. The link of dataset download 'https://storage.googleapis.com/t5-kgc-colab/data/data.zip' cannot be opened. Thanks.

**Comment by apoorvumang** [comment]
Hi, thanks for your interest and thank you for bringing this to our attention. The issue has been resolved and the link should be accessible now

**Comment by apoorvumang** [comment]
Closing for now, please reopen if not resolved

**Comment by gyf6666** [comment]
Hello naruto, can you share KGC data set with me?

**Comment by apoorvumang** [comment]
Unfortunately it got deleted, but you can probably find some information here https://github.com/uma-pi1/kgt5-context
